### Register a new user
POSThttp://example.com/auth/register/ 
Content-Type: application/json

{
  "password": "TestPassword123!",
  "email": "testuser@example.com"
}

### Login with the user to get access and refresh tokens
POSThttp://example.com/auth/login/
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "TestPassword123!"
}

### Refresh the access token
POSThttp://example.com/auth/refresh/
Content-Type: application/json

{
  "refresh": "PUT_REFRESH_TOKEN_HERE"
}

### Logout (invalidate refresh token)
POSThttp://example.com/auth/logout/
Content-Type: application/json

{
  "refresh": "PUT_REFRESH_TOKEN_HERE"
}